Command Bus
jorge07/ddd-playground pull request #19
Opened 2016-12-16 16:43 UTC by jorge07

2016-12-17 12:12 UTC, 1ma requested changes
needs correct composer.json

2016-12-17 12:12 UTC, 1ma commented on composer.lock
> +            "name": "league/tactician",
New dependencies have been introduced but the composer.*json* file is the same.

![fucky](http://i.imgur.com/IgU4Y.gif)

2016-12-17 12:12 UTC, 1ma commented on app/AppKernel.php
> +
Some men just want to watch the world burn.

2016-12-17 12:12 UTC, 1ma commented on src/Infrastructure/WalletBundle/Resources/config/application/use_case.yml
> +          - { name: tactician.handler, command: Leos\Application\UseCase\Wallet\Request\Find }
dat (missing) newline

2016-12-17 12:23 UTC, 1ma commented
Also, a couple of general questions:

- How does the Command Bus know which Handlers must execute which Commands? I have not seen any "mappings" of this kind anywhere, apart from the type hinting in the `handle` methods. If that's really enough for Tactician to figure out how should it work it is kinda cool.

- The PR doesn't add any middlewares, which, as far as I understand are the major motivator for using a Command Bus. So given this fact, how is this better than just injecting the handler(s) you need into each controller instead of the Command Bus?

2016-12-19 09:04 UTC, jorge07 commented
@1ma 
1 -> `src/Infrastructure/WalletBundle/Resources/config/application/use_case.yml` that's one of the files. Look at `src/**/use_case.yml` files.

2 -> You're right, doesn't add any middleware, but add the possibility to do it. The idea was use `Doctrine Middleware` but when I read in his doc that: `Each command you execute will now open and close a new transaction.` I refused because I don't wanna open a connection to the database if I don't need it. So, basically abstracts the UI of the Domain system, and you just need to know the command you wanna run.

2016-12-19 09:09 UTC, 1ma commented
LGTM now

2016-12-19 09:25 UTC, merged